# Generated by Django 5.1.7 on 2025-04-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_zip_code',
            new_name='shipping_zipcode',
        ),
    ]
